/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AyoubBani (https://sketchfab.com/AyoubBani)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rocket-b17a0f9f805c4fa7b978829006bbb57f
title: Rocket
*/

import React, { Suspense, useRef } from 'react'
import { useGLTF, OrbitControls } from '@react-three/drei'
import { Canvas, useFrame } from 'react-three-fiber';

 function Rocket({ ...props }) {
  const group = useRef()
  useFrame(()=> {
    group.current.rotation.z += 0.005
    group.current.rotation.y += 0.005
    
  })
  const { nodes, materials } = useGLTF('rocket.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={4}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder_white_0.geometry} material={materials.white} />
            <mesh geometry={nodes.Cylinder_red_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Cylinder_metal_0.geometry} material={materials.metal} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube_metal2_0.geometry} material={materials['metal.2']} />
          </group>
          <group position={[20.44, 20.34, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder001_metal_0.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cylinder001_window_glass_0.geometry} material={materials.window_glass} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={98.35}>
            <mesh geometry={nodes.Cylinder003_red_0.geometry} material={materials.material} />
          </group>
          <group position={[28.92, 21.84, 0]} rotation={[-Math.PI / 2, -0.17, 0]} scale={100}>
            <mesh geometry={nodes.Cube001_metal2_0.geometry} material={materials['metal.2']} />
          </group>
          <group position={[0, -41.75, 0.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder008_metal_0.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cylinder008_metal_0_1.geometry} material={materials.metal} />
          </group>
          <group position={[0.16, -52.23, 8.57]} rotation={[-Math.PI / 2, 0, 0]} scale={9.64}>
            <mesh geometry={nodes.Cube002_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
            <mesh geometry={nodes.Cube002_whiteSmoke_0_1.geometry} material={materials['white.Smoke']} />
            <mesh geometry={nodes.Cube002_whiteSmoke_0_2.geometry} material={materials['white.Smoke']} />
            <mesh geometry={nodes.Cube002_whiteSmoke_0_3.geometry} material={materials['white.Smoke']} />
            <mesh geometry={nodes.Cube002_whiteSmoke_0_4.geometry} material={materials['white.Smoke']} />
            <mesh geometry={nodes.Cube002_whiteSmoke_0_5.geometry} material={materials['white.Smoke']} />
            <mesh geometry={nodes.Cube002_whiteSmoke_0_6.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[9.24, -68.27, 16.27]} rotation={[-Math.PI / 2, 0, 0]} scale={3.78}>
            <mesh geometry={nodes.Cube005_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[-6.11, -63.37, 1.6]} rotation={[-Math.PI / 2, 0, 0]} scale={2.81}>
            <mesh geometry={nodes.Cube006_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[8.04, -71.26, 9.05]} rotation={[-Math.PI / 2, 0, 0]} scale={2.61}>
            <mesh geometry={nodes.Cube007_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[-1.58, -74.12, 13.92]} rotation={[-Math.PI / 2, 0, 0]} scale={1.65}>
            <mesh geometry={nodes.Cube008_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[-3.67, -65.49, 21.6]} rotation={[-Math.PI / 2, 0, 0]} scale={1.65}>
            <mesh geometry={nodes.Cube009_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[2.85, -60.52, 17.39]} rotation={[-Math.PI / 2, 0, 0]} scale={2.61}>
            <mesh geometry={nodes.Cube010_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[1.75, -67.55, 4.54]} rotation={[-Math.PI / 2, 0, 0]} scale={1.96}>
            <mesh geometry={nodes.Cube011_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[-11.38, -69.54, -1.11]} rotation={[-Math.PI / 2, 0, 0]} scale={1.65}>
            <mesh geometry={nodes.Cube012_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[-2.94, -67.55, 10.18]} rotation={[-Math.PI / 2, 0, 0]} scale={1.07}>
            <mesh geometry={nodes.Cube013_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[-8.11, -65.44, 11.31]} rotation={[-Math.PI / 2, 0, 0]} scale={3.78}>
            <mesh geometry={nodes.Cube014_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[0.22, -51.55, -7.5]} rotation={[-Math.PI / 2, 0, 2.01]} scale={8.72}>
            <mesh geometry={nodes.Cube015_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
            <mesh geometry={nodes.Cube015_whiteSmoke_0_1.geometry} material={materials['white.Smoke']} />
            <mesh geometry={nodes.Cube015_whiteSmoke_0_2.geometry} material={materials['white.Smoke']} />
            <mesh geometry={nodes.Cube015_whiteSmoke_0_3.geometry} material={materials['white.Smoke']} />
            <mesh geometry={nodes.Cube015_whiteSmoke_0_4.geometry} material={materials['white.Smoke']} />
            <mesh geometry={nodes.Cube015_whiteSmoke_0_5.geometry} material={materials['white.Smoke']} />
            <mesh geometry={nodes.Cube015_whiteSmoke_0_6.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[4.15, -63.13, -17.66]} rotation={[-Math.PI / 2, 0, 0.89]} scale={3.42}>
            <mesh geometry={nodes.Cube016_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[-8.9, -61.63, -12.24]} rotation={[-Math.PI / 2, 0, 0.89]} scale={2.54}>
            <mesh geometry={nodes.Cube017_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[3.62, -70.16, -19.14]} rotation={[-Math.PI / 2, 0, 0.89]} scale={2.36}>
            <mesh geometry={nodes.Cube018_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[2.89, -71.37, -8.46]} rotation={[-Math.PI / 2, 0, 0.89]} scale={1.5}>
            <mesh geometry={nodes.Cube019_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[9.2, -62.4, -2.6]} rotation={[-Math.PI / 2, 0, 0.89]} scale={1.5}>
            <mesh geometry={nodes.Cube020_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[6.95, -59.05, -11.12]} rotation={[-Math.PI / 2, 0, 0.89]} scale={2.36}>
            <mesh geometry={nodes.Cube021_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[-3.14, -66.91, -15.13]} rotation={[-Math.PI / 2, 0, 0.89]} scale={1.78}>
            <mesh geometry={nodes.Cube022_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[-13.39, -67.22, -10.6]} rotation={[-Math.PI / 2, 0, 0.89]} scale={1.5}>
            <mesh geometry={nodes.Cube023_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[-1.54, -65.42, -8.98]} rotation={[-Math.PI / 2, 0, 0.89]} scale={0.97}>
            <mesh geometry={nodes.Cube024_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[-2.72, -65.32, -4.15]} rotation={[0.74, 0, 2.25]} scale={[-3.42, 3.42, 3.42]}>
            <mesh geometry={nodes.Cube025_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[4.8, -74.39, 0.81]} rotation={[-Math.PI / 2, 0, 0.89]} scale={1.5}>
            <mesh geometry={nodes.Cube026_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[2.89, -78.14, -2.73]} rotation={[-Math.PI / 2, 0, 0.89]} scale={0.68}>
            <mesh geometry={nodes.Cube027_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
          <group position={[-13.56, -70.16, 5.36]} rotation={[-Math.PI / 2, 0, 0.89]} scale={2.36}>
            <mesh geometry={nodes.Cube028_whiteSmoke_0.geometry} material={materials['white.Smoke']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('rocket.glb')

export default function RocketModel() {
  return(
    <div style={{ width: "30rem", height: "70vh" }}>
  <Canvas>
  <ambientLight inensity={0.5}/>
  <Suspense fallback={null}>
     <Rocket />
  </Suspense>
</Canvas>
</div>
)};
